<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Platforms>x64</Platforms>
    <Configurations>Debug;Release</Configurations>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="2024.*" PrivateAssets="All" />
    <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="2024.*" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="BCCPlugIn.addin" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="RevitServerDownloader\**" />
    <None Include="RevitServerDownloader\**" />
    <Page Remove="RevitServerDownloader\**" />

    <Compile Remove="BCCInstaller\**" />
    <None Include="BCCInstaller\**" />
    <Page Remove="BCCInstaller\**" />
  </ItemGroup>
</Project>
